services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glpi-bot
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "33090:33090"
    volumes:
      - ./db:/app/db
      - ./web:/app/web
      - ./static:/app/static